// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: f4_fillings.sql

package database

import (
	"context"
	"time"
)

const insertF4FilingRecord = `-- name: InsertF4FilingRecord :exec
INSERT INTO f4_filings 
(accession_number, document_type, period_of_report, issuer_cik, issuerTradingSymbol,
rpt_owner_cik, rpt_owner_name, officer_title, created_at, form4_url)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertF4FilingRecordParams struct {
	AccessionNumber     string
	DocumentType        string
	PeriodOfReport      string
	IssuerCik           string
	Issuertradingsymbol string
	RptOwnerCik         string
	RptOwnerName        string
	OfficerTitle        string
	CreatedAt           time.Time
	Form4Url            string
}

func (q *Queries) InsertF4FilingRecord(ctx context.Context, arg InsertF4FilingRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertF4FilingRecord,
		arg.AccessionNumber,
		arg.DocumentType,
		arg.PeriodOfReport,
		arg.IssuerCik,
		arg.Issuertradingsymbol,
		arg.RptOwnerCik,
		arg.RptOwnerName,
		arg.OfficerTitle,
		arg.CreatedAt,
		arg.Form4Url,
	)
	return err
}
