// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: f4_fillings.sql

package database

import (
	"context"
	"time"
)

const insertF4FilingRecord = `-- name: InsertF4FilingRecord :many
INSERT INTO f4_filings 
(accession_number, document_type, period_of_report, issuer_cik, issuerTradingSymbol,
rpt_owner_cik, rpt_owner_name, officer_title, created_at, form4_url)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
) 
RETURNING accession_number, document_type, period_of_report, issuer_cik, issuertradingsymbol, rpt_owner_cik, rpt_owner_name, officer_title, created_at, form4_url
`

type InsertF4FilingRecordParams struct {
	AccessionNumber     string
	DocumentType        string
	PeriodOfReport      string
	IssuerCik           string
	Issuertradingsymbol string
	RptOwnerCik         string
	RptOwnerName        string
	OfficerTitle        string
	CreatedAt           time.Time
	Form4Url            string
}

func (q *Queries) InsertF4FilingRecord(ctx context.Context, arg InsertF4FilingRecordParams) ([]F4Filing, error) {
	rows, err := q.db.QueryContext(ctx, insertF4FilingRecord,
		arg.AccessionNumber,
		arg.DocumentType,
		arg.PeriodOfReport,
		arg.IssuerCik,
		arg.Issuertradingsymbol,
		arg.RptOwnerCik,
		arg.RptOwnerName,
		arg.OfficerTitle,
		arg.CreatedAt,
		arg.Form4Url,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []F4Filing
	for rows.Next() {
		var i F4Filing
		if err := rows.Scan(
			&i.AccessionNumber,
			&i.DocumentType,
			&i.PeriodOfReport,
			&i.IssuerCik,
			&i.Issuertradingsymbol,
			&i.RptOwnerCik,
			&i.RptOwnerName,
			&i.OfficerTitle,
			&i.CreatedAt,
			&i.Form4Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
