// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type F4Filing struct {
	AccessionNumber     string
	DocumentType        string
	PeriodOfReport      string
	IssuerCik           string
	Issuertradingsymbol string
	RptOwnerCik         string
	RptOwnerName        string
	OfficerTitle        string
	CreatedAt           time.Time
	Form4Url            string
}

type TickerCikMapping struct {
	Cik    string
	Ticker string
}
