// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type TickerCikMapping struct {
	ID     uuid.UUID
	Ticker string
	Cik    string
}
