// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticker_cik.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCIKByTicker = `-- name: GetCIKByTicker :one
SELECT cik from ticker_cik_mapping
WHERE ticker = $1
`

func (q *Queries) GetCIKByTicker(ctx context.Context, ticker string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCIKByTicker, ticker)
	var cik string
	err := row.Scan(&cik)
	return cik, err
}

const insertTickerCik = `-- name: InsertTickerCik :many
INSERT INTO ticker_cik_mapping 
(id, ticker, cik)
VALUES (
    $1,
    $2,
    $3
) 
RETURNING id, ticker, cik
`

type InsertTickerCikParams struct {
	ID     uuid.UUID
	Ticker string
	Cik    string
}

func (q *Queries) InsertTickerCik(ctx context.Context, arg InsertTickerCikParams) ([]TickerCikMapping, error) {
	rows, err := q.db.QueryContext(ctx, insertTickerCik, arg.ID, arg.Ticker, arg.Cik)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TickerCikMapping
	for rows.Next() {
		var i TickerCikMapping
		if err := rows.Scan(&i.ID, &i.Ticker, &i.Cik); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
