// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticker_cik.sql

package database

import (
	"context"
)

const getCIKByTicker = `-- name: GetCIKByTicker :one
SELECT cik from ticker_cik_mapping
WHERE ticker = ?
`

func (q *Queries) GetCIKByTicker(ctx context.Context, ticker string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCIKByTicker, ticker)
	var cik string
	err := row.Scan(&cik)
	return cik, err
}

const insertTickerCik = `-- name: InsertTickerCik :exec
INSERT INTO ticker_cik_mapping 
(ticker, cik)
VALUES (
    ?,
    ?
)
`

type InsertTickerCikParams struct {
	Ticker string
	Cik    string
}

func (q *Queries) InsertTickerCik(ctx context.Context, arg InsertTickerCikParams) error {
	_, err := q.db.ExecContext(ctx, insertTickerCik, arg.Ticker, arg.Cik)
	return err
}
